feat(operator): add nominate functionality to operator table
subspace/astral pull request #405
Opened 2023-12-20 14:12 UTC by natachadelarosa

2024-01-02 06:13 UTC, marc-aurele-besner approved these changes

2024-01-11 19:11 UTC, DianaPertseva commented
Can't connect a wallet, but on the frontend side looks great 👍

2024-01-12 03:15 UTC, marc-aurele-besner requested changes

2024-01-12 03:18 UTC, marc-aurele-besner commented
> Can't connect a wallet, but on the frontend side looks great 👍

It's strange, with the preview version if I connect all wallets or more than 1 wallet, then the wallet can't connect, but if I connect only one wallet it works fine. But, if I run it locally, I don't have this issue and can connect all my wallets...

2024-05-21 15:01 UTC, closed without merging