Feat/add stake wars section
subspace/astral pull request #565
Opened 2024-04-10 19:50 UTC by dnoishi

2024-04-11 02:56 UTC, marc-aurele-besner requested changes
Awesome, looking great!
I suggested a few changes, primarily to improve type safety.

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/index.tsx
> +  const { data, loading, error } = useQuery(GET_CURRENT_BLOCK_NUMBER, {
```suggestion
  const { data, loading, error } = useQuery<GetCurrentBlockNumberQuery>(GET_CURRENT_BLOCK_NUMBER, {
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/OperatorsList.tsx
> +  const { data, error, loading } = useQuery(GET_ALL_OPERATORS, {
```suggestion
  const { data, error, loading } = useQuery<GetAllOperatorsQuery>(GET_ALL_OPERATORS, {
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/OperatorsList.tsx
> +import type { OperatorsConnectionQuery } from 'gql/graphql'
```suggestion
import type { OperatorsConnectionQuery, GetAllOperatorsQuery } from 'gql/graphql'
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/NominatorList.tsx
> +  const { data, error, loading } = useQuery(GET_ALL_NOMINATORS, {
```suggestion
  const { data, error, loading } = useQuery<GetAllNominatorsQuery>(GET_ALL_NOMINATORS, {
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/NominatorList.tsx
> +import type { NominatorsConnectionQuery } from 'gql/graphql'
```suggestion
import type { NominatorsConnectionQuery, GetAllNominatorsQuery } from 'gql/graphql'
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/EndGame.tsx
> +  const { data, error, loading } = useQuery(GET_ALL_NOMINATORS, {
```suggestion
  const { data, error, loading } = useQuery<GetAllNominatorsQuery>(GET_ALL_NOMINATORS, {
```

2024-04-11 02:56 UTC, marc-aurele-besner commented on explorer/src/components/StakeWars/EndGame.tsx
> +import { SortingState } from '@tanstack/react-table'
```suggestion
import { SortingState } from '@tanstack/react-table'
import type { GetAllNominatorsQuery } from 'gql/graphql'
```

2024-04-15 13:24 UTC, marc-aurele-besner approved these changes
LGTM 🚀

2024-04-16 20:47 UTC, marc-aurele-besner submitted a review, later dismissed

2024-04-17 21:21 UTC, marc-aurele-besner reviewed
<img width="1002" alt="Screenshot 2024-04-17 at 5 18 35 PM" src="https://github.com/subspace/astral/assets/82244926/3a6a7784-255b-475e-90a9-94140ee4347b">

The count does not match the amount of rows in the first section (stake)

<img width="1103" alt="image" src="https://github.com/subspace/astral/assets/82244926/9a3dba82-02d3-4f74-b123-fc259f9d465e">

The account is shown in the id column and in the account column, instead of a increment or id. for the second section (nominators)

2024-04-23 14:36 UTC, marc-aurele-besner commented
I'm guessing we want this pr to target staging first :)

2024-04-25 14:47 UTC, jfrank-summit commented
We need to be able to see all of the rewards, not just the top accounts. It also needs to be exportable so that we can make a proper accounting of mainnet tokens earned.

2024-05-10 11:34 UTC, marc-aurele-besner approved these changes

2024-05-10 12:40 UTC, jfrank-summit commented
> We need to be able to see all of the rewards, not just the top accounts. It also needs to be exportable so that we can make a proper accounting of mainnet tokens earned.

@marc-aurele-besner was this addressed? The preview doesn't work anymore.

2024-05-10 13:15 UTC, marc-aurele-besner commented
> > We need to be able to see all of the rewards, not just the top accounts. It also needs to be exportable so that we can make a proper accounting of mainnet tokens earned.
> 
> @marc-aurele-besner was this addressed? The preview doesn't work anymore.

My last commit address it, but in a sloppy way.
It's now displaying the page navigation and download button, but if we end up with more rows than the query limit size (150) then the amount of pages will be limited to the amount of row the query return.

I created a separate issue, [to improve the logic of the Table components](https://github.com/subspace/astral/issues/582)

2024-05-10 14:37 UTC, jfrank-summit approved these changes

2024-05-10 18:16 UTC, merged