improve the filtering of Actions in Staking section especially for de…
subspace/astral pull request #726
Opened 2024-07-13 18:27 UTC by marc-aurele-besner

## improve the filtering of Actions in Staking section especially for deregistered op

2024-07-13 19:16 UTC, jfrank-summit commented
When slashed there shouldn't be any options.
![image](https://github.com/user-attachments/assets/d1e9bd4a-e296-46a0-bae1-ddc142cd3357)

2024-07-14 12:47 UTC, marc-aurele-besner commented
> When slashed there shouldn't be any options. ![image](https://private-user-images.githubusercontent.com/37932802/348499167-d1e9bd4a-e296-46a0-bae1-ddc142cd3357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjA5ODYsIm5iZiI6MTcyMDk2MDY4NiwicGF0aCI6Ii8zNzkzMjgwMi8zNDg0OTkxNjctZDFlOWJkNGEtZTI5Ni00NmEwLWJhZTEtZGRjMTQyY2QzMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDEyMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjQwZjI1NzAyODhiOGEwZGIwZmU1MjZiYTE3ZTNhOWY5ZTVlNDM4NGI0OTdiMDkxODI1ZmMwZWE4ZDVjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WScPs7eIWSPBij0E5bg3cFBYFI8NJXd_3RNQNH8EurE)

I did the change for the operator list, but when slashed, do the nominators or operators can still withdraw, or everything taken?

2024-07-14 19:19 UTC, jfrank-summit commented
> > When slashed there shouldn't be any options. ![image](https://private-user-images.githubusercontent.com/37932802/348499167-d1e9bd4a-e296-46a0-bae1-ddc142cd3357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NjA5ODYsIm5iZiI6MTcyMDk2MDY4NiwicGF0aCI6Ii8zNzkzMjgwMi8zNDg0OTkxNjctZDFlOWJkNGEtZTI5Ni00NmEwLWJhZTEtZGRjMTQyY2QzMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDEyMzgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NjQwZjI1NzAyODhiOGEwZGIwZmU1MjZiYTE3ZTNhOWY5ZTVlNDM4NGI0OTdiMDkxODI1ZmMwZWE4ZDVjOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WScPs7eIWSPBij0E5bg3cFBYFI8NJXd_3RNQNH8EurE)
> 
> I did the change for the operator list, but when slashed, do the nominators or operators can still withdraw, or everything taken?

Everything is taken.

2024-07-14 19:21 UTC, jfrank-summit commented on explorer/src/components/Operator/OperatorsList.tsx
The action dropdown is still showing up on the preview for me.

2024-07-15 10:46 UTC, marc-aurele-besner commented on explorer/src/components/Operator/OperatorsList.tsx
It should be fix now
![image](https://github.com/user-attachments/assets/750ffdc4-f830-4c31-af4a-66ba292f8e10)

2024-07-15 18:48 UTC, jfrank-summit requested changes

2024-07-15 19:14 UTC, marc-aurele-besner commented on explorer/src/components/Operator/NominationManagement.tsx
> +          )
yes it work, I just made a ticket to merge all the staking page together (except register) so after this PR I'll merge them all

2024-07-15 19:30 UTC, jfrank-summit approved these changes

2024-07-15 19:38 UTC, merged